version: '3'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: UV_DB
      MYSQL_USER: admin_UV_DB
      MYSQL_PASSWORD: 
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "8080:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile  # Usa el Dockerfile personalizado
    container_name: php
    restart: always
    ports:
      - "8007:80"
    volumes:
      - ./html:/var/www/html
