# Usar la imagen base de Go
#FROM golang:1.23-alpine

# Establecer el directorio de trabajo
#WORKDIR /app

# Copiar los archivos necesarios
#COPY go.mod go.sum ./
#RUN go mod download

#COPY . .

# Compilar el binario
#RUN go build -o main .

# Comando para ejecutar la aplicación
#CMD ["./main"]

#LO ANTERIOR ES PARA PRODUCCION

FROM golang:1.23-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del módulo Go (sin código fuente aún)
COPY go.mod go.sum ./
RUN go mod download

# El código fuente se montará como un volumen
CMD ["go", "run", "main.go"]
