version: "3.9"

services:
  app:
    build: .
    ports:
      - "8020:8080"
    environment:
      - DB_HOST=192.168.1.14
      - DB_PORT=3307
      - DB_USER=admin_UV_DB
      - DB_PASSWORD=
      - DB_NAME=UV_DB
